#Minikube dev environment.
#Dependencies:
#  - minikube runs directly on the host machine (driver=none)
#  - You have built the image locally as ferlabcrsj/etcd-backup:latest
#  - You changed the hostpath in the orchestration to match the specifics of your machine
#  - The following orchestrations are assumed to be running in the background:
#      - https://github.com/Ferlab-Ste-Justine/cqdg-environments/tree/master/local/minio
#  - The following bucket should exist in your minio: etcd-backups
#Howto:
#Type the following to launch the pod: kubectl apply -f dev.yml
#Type the following to ssh into the pod: kubectl exec -it etcd-backup-dev -- bash 
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: etcd
  name: etcd
spec:
  containers:
  - image: quay.io/coreos/etcd:v3.4.15
    imagePullPolicy: Never
    name: etcd-backup-dev
    env:
      - name: ETCD_LISTEN_CLIENT_URLS
        value: http://0.0.0.0:2379
      - name: ETCD_ADVERTISE_CLIENT_URLS
        value: http://etcd:2379
    resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
  name: etcd
spec:
  ports:
  - port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: etcd
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: etcd-backup-dev
  name: etcd-backup-dev
spec:
  volumes:
    - name: scripts
      hostPath:
        path: /home/eric/Projects/backup-images/etcd
  containers:
  - image: ferlabcrsj/etcd-backup:latest
    imagePullPolicy: Never
    name: etcd-backup-dev
    resources: {}
    workingDir: /opt/backup
    command: ["sleep", "infinity"]
    volumeMounts:
      - name: scripts
        mountPath: /opt/backup
        readOnly: true
    env:
      - name: ETCDCTL_ENDPOINTS
        value: http://etcd:2379
      - name: S3_ACCESS_KEY
        value: myaccess
      - name: S3_SECRET_KEY
        value: mysecret
      - name: S3_REGION
        value: myregion
      - name: S3_ENDPOINT
        value: http://minio:9000
      - name: S3_BUCKET
        value: etcd-backups
      - name: S3_BACKUP_MAX_AGE
        value: "30"
