#Minikube dev environment.
#Dependencies:
#  - minikube runs directly on the host machine (driver=none)
#  - You have built the image locally as ferlabcrsj/postgres-backup:latest
#  - You changed the hostpath in the orchestration to match the specifics of your machine
#  - The following orchestrations are assumed to be running in the background:
#      - https://github.com/Ferlab-Ste-Justine/cqdg-environments/tree/master/local/minio
#      - https://github.com/Ferlab-Ste-Justine/cqdg-environments/tree/master/local/postgres
#  - The following bucket should exist in your minio: postgres-backups
#Howto:
#Type the following to launch the pod: kubectl apply -f dev.yml
#Type the following to ssh into the pod: kubectl exec -it pg-backup-dev -- bash 
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: pg-backup-dev
  name: pg-backup-dev
spec:
  volumes:
    - name: scripts
      hostPath:
        path: /home/eric/Projects/backup-images/postgres
  containers:
  - image: ferlabcrsj/postgres-backup:latest
    imagePullPolicy: Never
    name: pg-backup-dev
    resources: {}
    workingDir: /opt/backup
    command: ["sleep", "infinity"]
    volumeMounts:
      - name: scripts
        mountPath: /opt/backup
        readOnly: true
    env:
      - name: PGHOST
        value: postgres
      - name: PGDATABASE
        value: postgres
      - name: PGUSER
        value: postgres
      - name: PGPASSWORD
        value: mypassword
      - name: S3_ACCESS_KEY
        value: myaccess
      - name: S3_SECRET_KEY
        value: mysecret
      - name: S3_REGION
        value: myregion
      - name: S3_ENDPOINT
        value: http://minio:9000
      - name: S3_BUCKET
        value: postgres-backups
      - name: S3_BACKUP_MAX_AGE
        value: "30"
