name: Publish Images Using Commit Hash

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Publish Images
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Publish Postgres Backup Image
      uses: Ferlab-Ste-Justine/action-push-image@master
      with:
        username: ${{ secrets.FERLAB_DOCKER_HUB_USER }}
        password: ${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}
        image: ferlabcrsj/postgres-backup
        tag_source: sha
        location: postgres
        dockerfile: postgres/Dockerfile